### ISSUE TITLE
Shear Center Position at weird position

### ISSUE THREAD

**Issue by fridolin11** [joaoadelazzari/FStr#5]
Dear Mr De Lazzari

First of all thank you very much for this amazing tool!
During usage, I saw that the shear center is generated at weird positions. For example if you 1:1 adopt the example for Polygonal Hollow Sections (PHS) and then click on "Geometric Properties" and visualize the shear center, it displays the shear center to the left, outside of the profile. For the closed circular profile with uniform wall thickness made from one material, I would expect that the shear center is in the middle of the profile.

Does the calculation of the shear center have an impact on the calculated load factor? If not than it isn't a problem for me, since I don't really need to know the shear center.

![image](https://user-images.githubusercontent.com/120100620/234523732-853438ef-00f0-44e5-a206-869cf9b232bf.png)

For reference: I am running Version 1.4.0 on Windows 11 with the matlab Runtime R2019a.

Kind regards,
Fridolin

**Comment by joaoadelazzari** [comment]
Dear Fridolin,

Thank you very much for reporting the issue with the bug. It appears that the shear center is not being calculated properly for the indicated Polygonal Hollow Section. Unfortunately, the software is not currently able to accurately calculate the shear center, torsion constant, polar radius of gyration, and warping constant for closed cross-sections, as the general formulation for these cross-sections has not yet been implemented in the software. However, it is important to note that in the Geometrical Properties window, there is a caption at the bottom of the window stating that the indicated geometrical properties with an asterisk (*) are not accurately measured (see picture below).

![image](https://user-images.githubusercontent.com/61322817/234531729-67e1684c-7167-4511-af14-6375baab6351.png)


However, the elastic buckling analysis is not affected by these geometrical properties. If you wish, I may send a figure below that illustrates the validation of the FStr software, compared to a solution from a finite element software, ANSYS. The figure is taken from a scientific article that can be accessed through the following link: https://doi.org/10.1002/cepa.1740

![image](https://user-images.githubusercontent.com/61322817/234532344-9b2f8622-7e79-4330-9d75-19d8bf93cb0a.png)

> Source: Batista, E. de Miranda, de Lazzari, J.A., Matsubara, G.Y. and Pfeil, M. (2022), Structural Dynamic and Buckling Behaviour of Steel Cold-formed Polygonal Conic Pole for Antennas Support. ce/papers, 5: 151-160. https://doi.org/10.1002/cepa.1740

Thank you for reporting the bug, and I hope you are enjoying the FStr software,

Warm Regards,

Joao Alfredo de Lazzari

**Comment by fridolin11** [comment]
Dear Joao Alfredo

Thank you for the quick reply! Silly me didn't see the caption ;)
That is truly a nice match between the Ansys and FStr Analysis, thank you for the link!

Kind regards,
Fridolin

**Comment by fridolin11** [comment]
Dear Mr de Lazzari

One more question came up while using your Tool. Is it possible to use it to determine the loadfactor in beams made from composite materials? If yes, do you maybe have any papers which I could use as reference? I did some tests and verified them with Ansys and got mixxed results. Sometimes it matched well and sometimes not at all.
Or do you generally advise against using Finite Strip Analysis for anisotropic materials?

Kind regards,
Fridolin

**Comment by joaoadelazzari** [comment]
Dear Fridolin,

Thank you for the question.
So far, there are no papers about validation of the FStr used for beams made from composite materials. However, I am working with composite materials and I have validate it, for beams and columns. Bellow, I can show a picture of a validation of a composite hat column, with orthotropic material properties, compared to other references [1,2].

Just a reminder, if you want to insert the orthotropic material properties in FStr, you must input the properties in a specific other: transverse elastic modulus, longitudinal elastic modulus, minor Poisson ratio, major Poisson ratio and shear modulus.
As an example of the picture bellow, the material properties vector to be inserted in the FStr would be: [7.58 206.85  0.011  0.3  4.82]

![image](https://github.com/joaoadelazzari/FStr/assets/61322817/feccb6e9-6142-4058-aa20-46e3348083bc)

References:
[1] Nuno Silvestre, Dinar Camotim, "GBT buckling analysis of pultruded FRP lipped channel members", Computers and Structures 81 (2003) 1889–1904. https://doi.org/10.1016/S0045-7949(03)00209-8

[2] Turvey GJ, Wittrick WH., "The influence of orthotropy on the stability of some multi-plate structures in compression", Aero Quart 1973;24(1):1–8. https://doi.org/10.1017/S0001925900006363
